# Generated by Django 2.0.6 on 2018-06-24 06:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books1', django.db.models.manager.Manager()),
            ],
        ),
    ]
